package cmt.getData.dao;

import cmt.getData.po.TblAppMarketingToolUsedtl;
import java.sql.SQLException;
import java.util.List;


public interface TblAppMarketingToolUsedtlDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMST.TBL_APP_MARKETING_TOOL_USEDTL
     *
     * @abatorgenerated Thu Sep 05 12:46:58 CST 2013
     */
    void insert(TblAppMarketingToolUsedtl record) throws SQLException;
    public List selectExample(List str)throws SQLException;
    public List sqlQuery(String sql);
}